// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqmiqnftbrzcyefjqbtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbWlxbmZ0YnJ6Y3llZmpxYnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODE4MDQsImV4cCI6MjA2OTM1NzgwNH0.jithmUSL6tYCp3ZDeFqOrvbYeyo1P4bUp-TXPIFO_CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});